### ISSUE TITLE
This doesn't seem to work with Xcode 9

### ISSUE THREAD

**Issue by jlubeck** [zackslash/XJourney#1]
And mainly because this folder /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreLocation.framework/Support/SimulationScenarios

Doesn't exist anymore. Have you found a way to make this work on Xcode 9?

**Comment by samjhorne** [comment]
After updating to XCode 9, I no longer see the 'support' directory under CoreLocation.Framework.  I'm running XCode 9.1 with iOS 11 simulators.

Anyone know where the .plist files for custom location simulation have gone?

**Comment by george-voaides** [comment]
@shmoogems 
Hey, according to a comment on the original blog post for xJourney it seems that the .plist files are now in 
/System/Library/Frameworks/CoreLocation.framework/Support/SimulationScenarios

**Comment by StephenClarkApps** [comment]
How do we get this updated

**Comment by zackslash** [comment]
Xcode has since moved on and this project is now archived
